---
- name: restart mariadb
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: restart rrdcached
  service:
    name: rrdcached
    state: restarted
    enabled: yes
